/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.8).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.gabrielsson.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.ArrayList;
import java.util.List;

@Api(value = "pizzaname")
public interface PizzaNameApi {

    @ApiOperation(value = "Get pizza name", nickname = "nameGet", notes = "Retrieve a pizza name for the given ingredients.", response = String.class, tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK", response = String.class)})
    @RequestMapping(value = "/name",
            produces = {"application/text"},
            method = RequestMethod.GET)
    ResponseEntity<String> nameGet(ArrayList<String> ingredients);
}
